### PR TITLE
Do not move back the pivot if the current is genesis

### LINKED ISSUE #787: Panicked when the CodeChain gets invalid header
```
#786789300 2018-10-04 18:55:46  P2P Worker #1 INFO network  New connection from 127.0.0.1:64287(1)
#786789300 2018-10-04 18:55:46  P2P Worker #2 INFO sync  New peer detected #Local V4:6602
#786789300 2018-10-04 18:55:46  P2P Worker #3 INFO sync  Peer #Local V4:6602 status update: total_score: 99999999999999999, best_hash: 0x649f…7bb9
#786789300 2018-10-04 18:55:47  P2P Worker #0 INFO sync  Peer #Local V4:6602 status update: total_score: 999999999999999, best_hash: 0xae5b…e30c

====================

stack backtrace:
   0:     0x7f881d5c5365 - backtrace::backtrace::libunwind::trace::hbcbc5d587d599392
                        at /home/gnu/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.7/src/backtrace/libunwind.rs:53
                         - backtrace::backtrace::trace::h1de0bba1bde4ca3b
                        at /home/gnu/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.7/src/backtrace/mod.rs:42
   1:     0x7f881d5c098e - backtrace::capture::Backtrace::new_unresolved::hcd174068355da6d3
                        at /home/gnu/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.7/src/capture.rs:88
   2:     0x7f881d5c08ec - backtrace::capture::Backtrace::new::h9bebf8127293178a
                        at /home/gnu/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.7/src/capture.rs:63
   3:     0x7f881c6ae4b7 - panic_hook::panic_hook::h4f9be8a1adb26cc9
                        at util/panic_hook/src/lib.rs:53

Thread 'P2P Worker #3' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:345

This is a bug. Please report it at:

    https://github.com/CodeChain-io/codechain/issues/new

Aborted (core dumped)
```
After the CodeChain gets a sequence of invalid header than it panic.

### PR DESCRIPTION
**Pull request by sgkim126**
It fixes #787

### CODE REVIEW

File: sync/src/block/downloader/header.rs [hunk 1]
```diff
@@ -133,9 +135,11 @@ impl HeaderDownloader {
             }
         } else {
             let pivot_header = self.pivot_header();
-            self.pivot = Pivot {
-                hash: pivot_header.parent_hash(),
-                total_score: self.pivot.total_score - pivot_header.score(),
+            if pivot_header.hash() != self.genesis_hash {
```
Comment (Kais-DkM) [inline sync/src/block/downloader/header.rs]: Let's check parent header's information rather than checking its hash with an external parameter.
Genesis header always has a parent hash of zero.

Comment (sgkim126) [reply sync/src/block/downloader/header.rs]: No, it's not.
https://github.com/CodeChain-io/codechain/blob/e1752be322cd0e84553ac522b9a33478ab2b5a23/core/res/cuckoo.json#L30 You can change the parent hash of the genesis block.

Comment (Kais-DkM) [reply sync/src/block/downloader/header.rs]: Oh, I didn't know that.
Then how about checking its block number?
